name: Redis on Alpine OS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build Alpine based Redis image
      run: |
         cd ./alpine 
         echo "${{ secrets.DOCKERPW }}" | docker login -u "jrpamid" --password-stdin
         docker build -t jrpamid/redis-alpine:6.0.9 --build-arg ALPINE_VER=3.12 --build-arg REDIS_VER=6.0.9 .
         docker push jrpamid/redis-alpine:6.0.9

